title: Moderwell Family
email: luke.moderwell@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  We're the Moderwells and this is our family journal.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://moderwell.family" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  lukemoderwell

# Build settings
permalink: pretty
markdown: kramdown

assets:
  source_maps: true # false on JEKYLL_ENV=production
  destination: "/assets"
  compression: true
  sources:
  - assets/css
  - assets/img


exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
