title: moderwell.family
email: luke.moderwell@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  We're the Moderwells and this is our family journal.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://moderwell.family" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  lukemoderwell

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
